---
language: node_js
node_js:
  - "4"
  - "6"
  - "8"

sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  chrome: stable

branches:
  only:
    - master
    - beta
    - /^greenkeeper.*$/

cache:
  directories:
    - $HOME/.npm
  yarn: false # switch to yarn once ember-cli-addon-tests is removed

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    - CXX=g++-4.8 WORKER_COUNT=2

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version
  - npm i -g bower # for ember-cli-addon-tests
